### ISSUE TITLE
Infografia 

### ISSUE THREAD

**Issue by isaireyesp1** [SistemasTecTlaxiaco/actividad-1-infografia-isaireyesp1#2]
[ciclo de vida de un sistema de software.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-isaireyesp1/files/12491676/ciclo.de.vida.de.un.sistema.de.software.pdf)

**Comment by DaisyOrtiz2** [comment]
16/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
